### ISSUE TITLE
Update Shopify API to `2024-10`

### ISSUE THREAD

**Issue by darylknight** [nmaier95/craft-shopify-product-fetcher#121]
### Description
The plugin docs say "Additionally (at the bottom of this screen), the Webhook subscriptions → Event version should be 2023-10."

This is getting outdated again. Is it time to update the docs and check this plugin works with the latest version from Shopify?

![image](https://github.com/craftcms/shopify/assets/1250017/ac32eb1e-822d-479d-ba6f-5f8d329c03bc)

**Comment by nfourtythree** [comment]
Hi @darylknight 

Thank you for raising this.

When we update the Shopify API version that the plugin uses we are forced to make it a major plugin version update. This is because it requires developers to change the settings in their Shopify apps. Because of this, we do not want to undertake this change too often as we understand the potential extra burden this can put on developers.

The other part is that we rely on the [Shopify API PHP SDK](https://github.com/Shopify/shopify-api-php) and have to wait until the [corresponding version](https://github.com/Shopify/shopify-api-php/tree/main/src/Rest) is in a release that we can point to.

This also means that currently, we are looking to keep the API version updated on, roughly, a yearly cycle. At the moment the plugin is using `2023-10` so when `2024-10 is fully released (and supported by the library) we will update the plugin.

We are open to revisiting this schedule if there are enough developers out there who feel the need for a quicker timeline.

We will update this issue when the new version is released.

Thanks!

**Comment by nfourtythree** [comment]
Hi

We have just published version 5.3.0 of the plugin which supports version `2024-10` of the Shopify API.

In this version, we have now added the ability to choose which version of the Shopify API you are running. This means in the future we will update the plugin when new versions of the Shopify API become available without having to do a major release.

Thanks!
